version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./soccer-solution/frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./soccer-solution/backend:/app
    ports:
      - "5678:5678"
    environment:
      - OMP_NUM_THREADS=8
      - MKL_THREADING_LAYER=GNU
